### PR TITLE
Fix Test-ServiceDaclPermission

### PR DESCRIPTION
**Pull request by sagishahar**
The Implementation was corrected such that the permissions of the effective user (i.e. nested groups) are also checked. Additionally, Get-ServiceDaclPermission was removed as it is not necessary. Lastly, a few other minor updates were made to increase efficiency.

### CODE REVIEW

**Comment by HarmJ0y** [comment]
Was this one meant for master? Happy to land it, just checking (landed https://github.com/PowerShellEmpire/PowerTools/pull/72)

**Comment by sagishahar** [comment]
Yes this one is for master. Thanks for landing the other PR.

**Comment by HarmJ0y** [comment]
Would it be easier for me to stop being a shitty code manager and just merge the powersploit_fixup branch to master? I'm thinking this might simplify things as opposed to having two branches with diverging code bases. If I kill this one and merge the powersploit branch into master, would it be too much of a pain to resubmit the additional logic changes? Apologies for making this more difficult than it should have been!!

**Comment by sagishahar** [comment]
I agree with you 100%, things will be more simplified and easier to manage if the branches are merged as you suggested. Unless we are going for the DACL solution instead of catching sc.exe errors no additional logic changes will be required. Please let me know your final decision about the matter but either way it won't be a pain at all so no worries ;)

**Comment by HarmJ0y** [comment]
Cool, closing this guy- the fixup branch is now merged.

**Pull request closed without merging**
