### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by Meatballs1**
Integrate some of the other changes into 2.0... Still some changes needed...

### CODE REVIEW

**Comment by Meatballs1** [comment]
@HarmJ0y What is your preferred branch for development from here on?

**Comment by HarmJ0y** [comment]
The 2.0 development got temporarily put on the backburner with Empire dev, should be kicking back up on it soon/shortly, so that should be all good.

**Comment by HarmJ0y** [comment]
Also ported the Get-NetGroup changes to the 2.0 branch.

**Comment by HarmJ0y** [comment]
The 2.0 development got temporarily put on the backburner with Empire dev, but trying to kick it back up now. We're going to be testing the branch some more next week, and will hopefully merge soonish. It has some substantial usage changes from the current master branch, so want to make sure it's done right.

That said, and new mods would be appreciated in the 2.0 branch if possible. I went ahead and ported your recent changes to master into the 2.0 branch (Get-NetGroup/etc.)

**Pull request merged**
